pipeline:
  deploy:
    image: centos:centos6
    commands:
      - rm -Rf /var/www/html/soon2
      - mkdir -p /var/www/html/soon2
      - cp -Rf * /var/www/html/soon2/
    when:
      event: push
      branch: master
    volumes:
      - /var/www/html:/var/www/html
